### ISSUE TITLE
Configure webcam

### ISSUE THREAD

**Issue by seichold** [memhamwan/memhamwan.github.io#53]
The Camera needs to: 
- [ ] Configured for the Site IP it needs
- [ ] Mounting solution validated

**Comment by turnrye** [comment]
@seichold Ill add this to the inventory tracker too and will bring the label to the work party.

**Comment by turnrye** [comment]
https://github.com/memhamwan/inventory/issues/27

**Comment by turnrye** [comment]
- [ ] Add the camera to DNS
- [ ] Add the camera to monitoring; see https://github.com/memhamwan/fleet-apps/issues/2

**Comment by turnrye** [comment]
This issue is done; the next parts of it are on memhamwan/fleet-apps#2
